
library("RCurl")
library("curl")
library("plyr")
library("dplyr")
library("stringr")
library("readxl")
library("sf")
library("tidyverse")
library("arcgisbinding")
library("RPyGeo")
library("rgdal")
#library("reticulate")
library("lubridate")
arc.check_product()
library(utils, lib.loc ="C:/Users/tsink/Documents/R/win-library/3.5")